### ISSUE TITLE
在访问路由http://172.16.13.183:7001/test  时报下面的错误，其它路由都ok,怎么解决？

### ISSUE THREAD

**Issue by DragWeb** [hubcarl/egg-vue-webpack-boilerplate#12]
2017-07-25 22:05:18,793 ERROR 18442 [test/test.js] server render bundle error, try client render, the server render error TypeError: Cannot read property 'render' of undefined
    at normalizeRender (/Users/dang/work/egg-vue-webpack-boilerplate/node_modules/vue-server-renderer/build.js:6864:19)
    at render (/Users/dang/work/egg-vue-webpack-boilerplate/node_modules/vue-server-renderer/build.js:7211:5)
    at Object.renderToString (/Users/dang/work/egg-vue-webpack-boilerplate/node_modules/vue-server-renderer/build.js:7647:9)
    at /Users/dang/work/egg-vue-webpack-boilerplate/node_modules/vue-server-renderer/build.js:7956:22
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by DragWeb** [comment]
没有安装 npm install easywebpack-cli -g  导致的

**Comment by KELEN** [comment]
请问我全局安装了，test还是不能访问怎么解决呢？

**Comment by KELEN** [comment]
@DragWeb 请问我全局安装了，test还是不能访问怎么解决呢？

**Comment by DragWeb** [comment]
@KELEN 是不是router或者controller写的有问题？下面是我的写法参考下
```javascript
// router.js
module.exports = app => {
    app.get('/app/doc', 'doc.index')
}
```
```javascript
// controller/doc.js
module.exports = app => { 
  return class DocController extends app.Controller {
    * index() {
      const { ctx } = this
      yield ctx.renderClient('doc/doc.js')
    }
  }
}
```
```
// app/web/page/doc/doc.js
import App from 'app';
import Layout from 'component/layout/normal';
import Doc from './doc.vue';

App.component(Layout.name, Layout);

export default App.init({
  ...Doc
});

```
