### ISSUE TITLE
Error: spawn easywebpack ENOENT

### ISSUE THREAD

**Issue by Eric-Zhong** [hubcarl/egg-vue-webpack-boilerplate#21]
windows 7 下， 我执行了
git clone ....
npm install
npm install easywebpack --save-dev

然后准备Build prod时报错。 我怎么办才好呢？

过程如下：
C:\Users\xuzho\Work\Nodejs\egg-vue-webpack-boilerplate>npm run build

> egg-vue-webpack-boilerplate@2.0.0 build C:\Users\xuzho\Work\Nodejs\egg-vue-webpack-boilerplate
> cross-env easywebpack build prod

'easywebpack' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn easywebpack ENOENT
    at notFoundError (C:\Users\xuzho\Work\Nodejs\egg-vue-webpack-boilerplate\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\xuzho\Work\Nodejs\egg-vue-webpack-boilerplate\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\xuzho\Work\Nodejs\egg-vue-webpack-boilerplate\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-vue-webpack-boilerplate@2.0.0 build: `cross-env easywebpack build prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-vue-webpack-boilerplate@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xuzho\AppData\Roaming\npm-cache\_logs\2017-08-20T15_29_53_082Z-debug.log

**Comment by hubcarl** [comment]
@Eric-Zhong   cli命令行的话，请安装： npm install easywebpack-cli -g

**Comment by Eric-Zhong** [comment]
@hubcarl 多谢！我在Mac上可能好早前就安装过了，所以后面在使用过程中没太注意这个命令！Windows下就按默认操作搞了。问题已解决！
