### ISSUE TITLE
1.3.0 在windows 10 下 npm start Build 失败！

### ISSUE THREAD

**Issue by Eric-Zhong** [hubcarl/egg-vue-webpack-boilerplate#22]
ERROR in ./~/babel-loader/lib!./app/web/framework/vue/entry/client-loader.js!./app/web/page/about/about.vue
    Module not found: Error: Can't resolve 'Coilerplate.1.3.0appwebpageaboutabout.vue' in 'C:\boilerplate.1.3.0\app\web\page\about'
     @ ./~/babel-loader/lib!./app/web/framework/vue/entry/client-loader.js!./app/web/page/about/about.vue 13:41-96
     @ multi (webpack)-hot-middleware/client?path=http://127.0.0.1:9000/__webpack_hmr&noInfo=false&reload=false&quiet=false babel-loader!./app/web/framework/vue/entry/client-loader.js!./app/web/page/about/about.vue

...

2017-08-22 23:04:33,097 ERROR 20420 [-/127.0.0.1/-/45ms GET /] nodejs.TypeError: Cannot read property 'index/index.js' of undefined
    at Resource.inject (C:\boilerplate.1.3.0\node_modules\egg-view-vue-ssr\lib\resource.js:152:44)
    at Object.render (C:\boilerplate.1.3.0\node_modules\egg-view-vue-ssr\app\extend\context.js:30:39)
    at render.next (<anonymous>)
    at onFulfilled (C:\boilerplate.1.3.0\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by hubcarl** [comment]
@Eric-Zhong windows问题已修复， 请重新安装依赖验证一下，另外项目里面：egg-vue-webpack-boilerplate/app/web/framework/vue/entry/client-loader.js 和egg-vue-webpack-boilerplate/app/web/framework/vue/entry/server-loader.js 有修改 ， this.resourcePath 改为
 this.resourcePath.replace(/\\/g, '\\\\')

**Comment by hubcarl** [comment]
https://github.com/hubcarl/egg-vue-webpack-boilerplate/issues/24
