### ISSUE TITLE
demo示例服务端渲染失败 Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by Yunfly** [hubcarl/egg-vue-webpack-boilerplate#25]
```
2017-09-06 14:16:13,608 ERROR 11612 [index/index.js] server render bundle error, try client render, the server render error TypeError: Cannot read property 'render' of undefined
    at normalizeRender (H:\egg-vue\egg-vue-webpack-boilerplate\node_modules\_vue-server-renderer@2.4.2@vue-server-renderer\build.js:6864:19)
    at render (H:\egg-vue\egg-vue-webpack-boilerplate\node_modules\_vue-server-renderer@2.4.2@vue-server-renderer\build.js:7211:5)
    at Object.renderToString (H:\egg-vue\egg-vue-webpack-boilerplate\node_modules\_vue-server-renderer@2.4.2@vue-server-renderer\build.js:7647:9)
    at H:\egg-vue\egg-vue-webpack-boilerplate\node_modules\_vue-server-renderer@2.4.2@vue-server-renderer\build.js:7956:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by Yunfly** [comment]
qin
