### ISSUE TITLE
Win10开发单页面应用的时候 写在template里面的style没有被编译

### ISSUE THREAD

**Issue by Yunfly** [hubcarl/egg-vue-webpack-boilerplate#26]
在模板内通过import也不行

**Comment by Yunfly** [comment]
我是把一些组件写在page/app/view里面的，这样不行吗?

**Comment by Yunfly** [comment]
找到原因了，是组件调用的时候，因为已经是异步调用了，在router.js中再使用
```
const Login = ()=>import('../views/login/login.vue');
```
这种形式引入组件就会出问题

**Comment by hubcarl** [comment]
这个问题我需要验证 一下，如果有问题，你可以先写成 独立css试试

**Comment by Yunfly** [comment]
改一些引入写法就可以了，本身就用了vuex-router-sync  我那么做还想是多此一举了

**Comment by Yunfly** [comment]
不对啊，我细查了下vuex-router-sync这个好像不是我想的那样，如果我把组件通过异步方式引入，就会在```app/view```下生成chunk.js 而不是在```/app/view/app``` 下面但是控制台就会报路径错误
```
{ Error: Cannot find module '0.js' from 'H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\app\view\app'
    at Function.module.exports [as sync] (H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_resolve@1.4.0@resolve\lib\sync.js:40:15)
    at r (H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_vue-server-renderer@2.4.4@vue-server-renderer\build.js:7760:44)
    at Function.module.exports.e.e (__vue_ssr_bundle__:1:283)
    at d (__vue_ssr_bundle__:1:146537)
    at H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_vue-router@2.7.0@vue-router\dist\vue-router.common.js:1711:17
    at H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_vue-router@2.7.0@vue-router\dist\vue-router.common.js:1738:66
    at Array.map (<anonymous>)
    at H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_vue-router@2.7.0@vue-router\dist\vue-router.common.js:1738:38
    at Array.map (<anonymous>)
    at flatMapComponents (H:\teste\egg-vue-webpack-boilerplate-feature-webpack2\node_modules\_vue-router@2.7.0@vue-router\dist\vue-router.common.js:1737:26) code: 'MODULE_NOT_FOUND' }

```

**Comment by Yunfly** [comment]
复现起来也很简单。就像这样
```
const ListView = ()=> import ('./list');
const DetailView = ()=>import('./detail')
```
异步引入这两个组件

**Comment by Yunfly** [comment]
@hubcarl

**Comment by hubcarl** [comment]
好，明天看看

**Comment by hubcarl** [comment]
这事搞忘了，国庆在家看看

**Comment by hubcarl** [comment]
@Yunfly  这个服务端渲染， impor vue 可以了， 需要用easywebpack-vue 3.5.1以上版本

**Comment by hubcarl** [comment]
@Yunfly  这个服务端渲染， impor vue 可以了， 需要用easywebpack-vue 3.5.1以上版本。 相关问题见：https://github.com/hubcarl/egg-vue-webpack-boilerplate/issues/46 和 https://zhuanlan.zhihu.com/p/32887257
