### ISSUE TITLE
server render bundle error, try client render, the server render error ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dbsg** [hubcarl/egg-vue-webpack-boilerplate#31]
2017-10-11 16:10:54,491 ERROR 3081 [story/story.js] server render bundle error, try client render, the server render error ReferenceError: window is not defined
    at VueComponent.data (__vue_ssr_bundle__:4820:19)
    at VueComponent.mergedInstanceDataFn (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:1150:21)
    at getData (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:3228:17)
    at initData (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:3187:7)
    at initState (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:3118:5)
    at VueComponent.Vue._init (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:4289:5)
    at new VueComponent (/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue/dist/vue.runtime.common.js:4461:12)
    at __vue_ssr_bundle__:1735:15
    at /Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue-server-renderer/build.js:7803:43
    at /Users/dbsg/WebstormProjects/page_8pig_com/node_modules/vue-server-renderer/build.js:7800:14

这个错误的原因是啥啊，还有index.js和layout.html哪个是基本模版啊，首页好像用的是layout,里面的story用的是index.js，，，菜鸟求解答

**Comment by ZyJoey** [comment]
服务端渲染失败就会启用前端渲染，错误原因是服务端没有window对象，你看看哪里有用到这个，加个判断 前端环境下执行这块代码就行了~

**Comment by dbsg** [comment]
@ZyJoey 多谢，已经找到原因了，不过在服务器也会渲染失败，原因是regeneratorRuntime is not defined，我看导个包，看能不能解决
