### ISSUE TITLE
TypeError: Cannot read property 'default' of null

### ISSUE THREAD

**Issue by callmez** [hubcarl/egg-vue-webpack-boilerplate#33]
新建的项目运行`build`报错

```js
a git:(master) ✗ npm run build

> a@3.0.2 build /Users/test/project/a
> cross-env easywebpack build prod

easywebpack: install webpack dynamic plugin npm module:
 [ 'imagemin-webpack-plugin@^1.5.2' ]
/Users/test/project/a/node_modules/easywebpack/lib/base.js:318
            Clazz = Clazz[configInfo.entry];
                                    ^

TypeError: Cannot read property 'default' of null
    at Object.keys.forEach.name (/Users/test/project/a/node_modules/easywebpack/lib/base.js:318:37)
    at Array.forEach (<anonymous>)
    at WebpackClientBuilder.createPlugin (/Users/test/project/a/node_modules/easywebpack/lib/base.js:303:26)
    at WebpackClientBuilder.createWebpackPlugin (/Users/test/project/a/node_modules/easywebpack/lib/base.js:354:17)
    at WebpackClientBuilder.create (/Users/test/project/a/node_modules/easywebpack/lib/base.js:365:21)
    at WebpackClientBuilder.create (/Users/test/project/a/node_modules/easywebpack/lib/client.js:67:18)
    at builders.forEach.builder (/Users/test/project/a/node_modules/easywebpack/lib/builder.js:18:41)
    at Array.forEach (<anonymous>)
    at Object.exports.getWebpackConfig (/Users/test/project/a/node_modules/easywebpack/lib/builder.js:13:12)
    at Object.exports.getWebpackConfig.config [as getWebpackConfig] (/Users/test/project/a/node_modules/easywebpack-vue/index.js:9:37)
    at Object.exports.build.config [as build] (/usr/local/lib/node_modules/easywebpack-cli/lib/builder.js:53:37)
    at Command.program.command.description.action.env (/usr/local/lib/node_modules/easywebpack-cli/bin/cli.js:59:13)
    at Command.listener (/usr/local/lib/node_modules/easywebpack-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/local/lib/node_modules/easywebpack-cli/node_modules/commander/index.js:635:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! a@3.0.2 build: `cross-env easywebpack build prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the a@3.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2017-10-12T09_47_12_127Z-debug.log

```

**Comment by hubcarl** [comment]
@callmez  你重新运行一下试试，另外检查一下node_modules/imagemin-webpack-plugin 是否安装成功

**Comment by hubcarl** [comment]
@callmez  测试发现，在node8+下面  imagemin-webpack-plugin 插件动态安装失败，请手动安装一下：npm i imagemin-webpack-plugin --save-dev
