### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by z1z2** [hubcarl/egg-vue-webpack-boilerplate#55]
OS: macOS 10.13.2
node: 8.9.1
克隆骨架项目，用 `egg-bin dev` 运行，点击几次不同的 tab 后，终端出现

```
(node:46178) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 webpack_read_file_memory_content listeners added. Use emitter.setMaxListeners() to increase limit
2018-01-20 17:49:40,910 INFO 46178 [-/192.168.6.102/-/3ms GET /pager?pageIndex=1&pageSize=10] [access] 192.168.6.102: - GET /pager?pageIndex=1&pageSize=10 HTTP/200 1862 http://192.168.6.102:7001/dynamic 2 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

  Error: read ECONNRESET
      at _errnoException (util.js:1024:11)
      at TCP.onread (net.js:615:25)
```

**Comment by ZQun** [comment]
我也是用的egg-bin但没有遇到问题，配置到了package.json里面
```
    "start": "eggctl start --port=7001 --daemon --sticky",
    "stop": "eggctl stop",
    "restart": "npm stop && npm start",
    "dev": "egg-bin dev --port=7001 --sticky",
```

**Comment by z1z2** [comment]
我加了 sticky 参数，之前那个 warning 没出现了，但还是有这个
```
2018-01-22 10:51:14,158 WARN 155000 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2018-01-22 10:51:14.163] [cfork:master:155036] don't fork new work (refork: false)
2018-01-22 10:51:14,166 INFO 155036 [master] app_worker#1:155684 disconnect, suicide: true, state: disconnected, current workers: ["2"]
[2018-01-22 10:51:14.186] [cfork:master:155036] worker:155684 exit (code: null, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
```

**Comment by ZQun** [comment]
检查一下你安装依赖的版本呢，还有你是用的最新提交的master吗
```
"egg-bin": "^4.3.7",
```

**Comment by z1z2** [comment]
egg-bin 升级了，代码是刚 clone 的。Windows 10 下也有相同问题。

```
egg-bin dev --port=7001 --sticky
```

```
2018-01-22 12:01:29,946 INFO 160640 [-/127.0.0.1/-/31ms GET /dynamic] [access] 127.0.0.1: - GET /dynamic HTTP/200 194636 http://127.0.0.1:7001/client 31 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
(node:160640) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 webpack_read_file_memory_content listeners added. Use emitter.setMaxListeners() to increase limit
2018-01-22 12:01:30,204 INFO 160640 [-/127.0.0.1/-/2ms GET /pager?pageIndex=1&pageSize=10] [access] 127.0.0.1: - GET /pager?pageIndex=1&pageSize=10 HTTP/200 1862 http://127.0.0.1:7001/dynamic 1 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
```

**Comment by hubcarl** [comment]
这个出现不影响本地开发的。出现的这个原因是因为同一时间进程间通信频繁的提示，我们有时也会出现，但不影响本地开发。

**Comment by z1z2** [comment]
感谢答复。这个问题确实不影响开发，出现 warning 后页面会重新加载，一般也不影响使用。不过我们这里的特殊情况是，页面里有个很大的 3D 模型，重新加载体验就不好了。
顺便再请教一下，warning 中提到的 `emitter.setMaxListeners() ` 应该加在什么地方？设置一个较大的数值是不是就可以降低 warning 的概率？

**Comment by hubcarl** [comment]
@z1z2 这个也具体需要看一下，具体进程通信在 egg-webpack 里面

**Comment by hubcarl** [comment]
可以通过 app.messenger.setMaxListeners() 设置，具体代码在  egg-core 。egg-webpack 已发布 3.3.1

**Comment by z1z2** [comment]
@hubcarl 多谢了
