### ISSUE TITLE
引入了iview插件，提示服务器端渲染失败采用客户端渲染，报错

### ISSUE THREAD

**Issue by ZQun** [hubcarl/egg-vue-webpack-boilerplate#7]
麻烦帮看下，谢谢

-----------Err------------

webpack: Compiled successfully.
2017-06-22 18:46:41,458 ERROR 19960 [admin/admin.js] server render bundle error, try client render, the server render error ReferenceError: window is not defined
    at Object.defineProperty.value (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:233:51)
    at __webpack_require__ (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:30:30)
    at Object.defineProperty.value (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:6829:15)
    at __webpack_require__ (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:30:30)
    at Object.<anonymous> (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:25513:3)
    at __webpack_require__ (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:30:30)
    at Object.defineProperty.value (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:4131:14)
    at __webpack_require__ (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:30:30)
    at Object.<anonymous> (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:26608:14)
    at __webpack_require__ (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:30:30)
    at module.exports.rawScriptExports (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:76:18)
    at /Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:79:10
    at webpackUniversalModuleDefinition (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:3:20)
    at Object.<anonymous> (/Users/Qun/WebstormProjects/egg/egg-vue-webpack-boilerplate-master/node_modules/iview/dist/iview.js:10:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
[Vue warn]: Property or method "title" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

(found in <Root>)
[Vue warn]: Property or method "keywords" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

(found in <Root>)
[Vue warn]: Property or method "description" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

(found in <Root>)
[Vue warn]: Property or method "baseClass" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

(found in <Root>)
2017-06-22 18:46:41,467 INFO 19960 [-/::1/-/179ms GET /admin/] [access] ::1: - GET /admin/ HTTP/200 181581 - 176 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by hubcarl** [comment]
the server render error ReferenceError: window is not defined---  这说明iview不支持服务器端渲染

**Comment by ZQun** [comment]
window is not defined，把iview.js的报错window改了就可以渲染了

**Comment by ZQun** [comment]
还想问一下，怎样对某些页面配置不进行服务器端渲染的设置？

**Comment by hubcarl** [comment]
前端渲染： https://github.com/hubcarl/egg-vue-webpack-boilerplate/issues/1
