### ISSUE TITLE
BUG: npm run dev报错ENOENT: no such file or directory, open '.../egg-vue-webpack-boilerplate/app/view/node_modules/1.js'

### ISSUE THREAD

**Issue by boyangwang** [hubcarl/egg-vue-webpack-boilerplate#84]
命令行报错, localhost:7001卡在`正在努力编译中...`页面
```
✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/app/view/node_modules/1.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at asyncChunk.files.forEach.filename (/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/node_modules/easywebpack-vue/config/plugin/vue-ssr-dynamic-chunk-webpack-plugin/index.js:31:16)
    at Array.forEach (<anonymous>)
    at asyncChunks.forEach.asyncChunk (/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/node_modules/easywebpack-vue/config/plugin/vue-ssr-dynamic-chunk-webpack-plugin/index.js:28:28)
    at Set.forEach (<anonymous>)
    at compilation.chunks.forEach.chunk (/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/node_modules/easywebpack-vue/config/plugin/vue-ssr-dynamic-chunk-webpack-plugin/index.js:27:36)
    at Array.forEach (<anonymous>)
    at compiler.hooks.emit.tap (/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/node_modules/easywebpack-vue/config/plugin/vue-ssr-dynamic-chunk-webpack-plugin/index.js:20:26)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wang.boyang/Projects/src/github.com/dexDev/egg-vue-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:14:1)
webpack build [========================================================= ] 98% (5.2 seconds)Total precache size is about 0 B for 0 resources.
webpack build [=========================================================] 100% (5.2 seconds)

Build completed in 5.198s
```

egg-vue-webpack-boilerplate版本: master@cf853194ef4a8afc0855175a1d9aaae86b08dce2  feat: use egg-bin and egg-scripts
node版本 : 8.11.3
OS版本: OSX high sierra 10.13.6

按照快速开始的步骤做的, clone repo, install, run dev, 然后卡在努力编译中页面.

奇怪的是命令行输出最后看起来像是成功的

**Comment by boyangwang** [comment]
fix是找到了, 就`mkdir egg-vue-webpack-boilerplate/app/view/node_modules`. 看起来是一个vue-ssr-dynamic-chunk-webpack-plugin的bug
